### PR TITLE
chore(webpack): Upgrade to webpack 2.2

### PR DESCRIPTION
**Pull request by codesuki**
Upgraded to webpack 2.2.
Downgraded css-loader to 0.14.5 because of performance regression. Build became ~2s faster.
Enabled caching for babel. Build became ~5s faster.

Could exchange css-loader for raw-loader for another ~1s.

I tested if it compiles fine doing `yarn run dev`. Maybe someone could check it out and confirm.

### CODE REVIEW

**Comment by traviskaufman** [comment]
😍 Thank you _so much_ for doing this! It's been on my radar since Webpack2 hit beta. Sorry for the delay in the review; I'll be going over it today.

**Comment by traviskaufman** [comment]
@codesuki I checked out the branch and ran `npm run dist` and got some errors when `npm run build:min` was executing:

screen shot 2017-02-07 at 16 25 49

Looks like uglifyJS is choking on babel's output? Could be related to https://github.com/webpack/webpack/issues/2972

**Comment by codesuki** [comment]
Upgrading webpack seriously is a chore hahaha
I can understand you didn't do it yet. 

Thanks for testing! I will try to fix it today. 
I have an idea how to disable modules only during testing too.

**Comment by codesuki** [comment]
Fixed! And tree shaking should work now although I don't know how to confirm it.

**Comment by sgomes** [comment]
LGTM. Rebasing and merging!

Thanks again, @codesuki!

**Comment by codesuki** [comment]
Glad it worked!

**Comment by amojicamu** [comment]
Hi @traviskaufman, I was following [https://github.com/material-components/material-components-web/tree/master/packages/mdc-textfield](this) and [https://github.com/material-components/material-components-web/tree/master/framework-examples/angular2/src](this) while integrating with Angular (angular-cli generated, exported webpack.config and webpack.prod.config). It turns out this exact issue happens while building the prod version. Maybe you could add some hint or note on the integration guides. Since ng client uses angular 4 & webpack 2, transpiling is necessary for tree shacking with uglify.

Something similar to this in webpack.prod.config
```
"rules": [
    //{
    //    "enforce": "pre",
    //    "test": /\.js$/,
    //    "loader": "source-map-loader",
    //    "exclude": [
    //      /\/node_modules\//
    //    ]
    //},
    {
        "enforce": "pre",
        "test": /\.(js|jsx)$/,
        "use": [
        {
            "loader": 'babel-loader',
            "options": {
                "presets": ['es2015'],
            },
        },
        ],
        "exclude": [
        /\/node_modules\//
        ]
    },
```

I hope this helps anyone else running into this issue while integrating with Angular.

**Pull request merged**
