### PR TITLE
fix(toolbar): rename ambiguous identifiers (#765)

### LINKED ISSUE #765: Change MDC-toolbar flexible behavior adapter and constant name to remove ambiguity
### What MDC-Web Version are you using?

0.11.1

### What browser(s) is this bug affecting?

Tested on electron 1.6.7 initially (so Chromium?) and reproduced in codepen on Chrome 58.0.3029.110 (64-bit).

### What OS are you using?

Windows 8.1 64-bit

### What are the steps to reproduce the bug?

Please refer to [this pen](https://codepen.io/griest024/pen/pPMOdV?editors=1011) to reproduce the bug. The functions in question start on line 47 and 60.

### What is the expected behavior?

I would think that the foundation should only try to obtain information about the flexible row element only if it exists. That is, `getFlexibleRowElementOffsetHeight()` and `setStyleForFlexibleRowElement()` should only be called if `hasFlexibleRow_` is `true`. Since flexible is not a required mode of the toolbar, the element itself should be optional.

### What is the actual behavior?

`getFlexibleRowElementOffsetHeight()` and `setStyleForFlexibleRowElement()` are called whenever `init()` is called, regardless of the value of `hasFlexibleRow_`. This produces a `TypeError: Cannot read property 'offsetHeight' of undefined` since the flexible row element is undefined.

### Any other information you believe would be useful?

Note that the toolbar is in waterfall mode: `<header class="mdc-toolbar mdc-toolbar--fixed mdc-toolbar--waterfall mdc-theme--primary">` and *not* in flexible mode.

Here is a more informative stack trace than the one on codepen:
```
TypeError: Cannot read property 'offsetHeight' of undefined
    at Object.getFlexibleRowElementOffsetHeight (eval at <anonymous> (http://localhost:9080/renderer.js:1552:1), <anonymous>:58:64)
    at MDCToolbarFoundation.initKeyRatio_ (eval at <anonymous> (http://localhost:9080/renderer.js:1288:1), <anonymous>:168:47)
    at MDCToolbarFoundation.init (eval at <anonymous> (http://localhost:9080/renderer.js:1288:1), <anonymous>:95:10)
    at VueComponent.mounted (eval at <anonymous> (http://localhost:9080/renderer.js:1552:1), <anonymous>:76:21)
```

So it appears that [this line](https://github.com/material-components/material-components-web/blob/43cef6c06b66874c74449cc31072e03a17d239f1/packages/mdc-toolbar/foundation.js#L166) and [this one](https://github.com/material-components/material-components-web/blob/43cef6c06b66874c74449cc31072e03a17d239f1/packages/mdc-toolbar/foundation.js#L206) are to blame.

### PR DESCRIPTION
**Pull request by griest024**
fixes #765: rename identifiers related to flexible row element offset height to first row element
offset height

BREAKING CHANGE: rename the adapter method getFlexibleRowElementOffsetHeight to
getFirstRowElementOffsetHeight

@yeelan0319

### CODE REVIEW

**Comment by griest024** [comment]
Would you like this PR to include changes to documentation?

**Comment by griest024** [comment]
@traviskaufman `packages/mdc-slider/README.md` does not exist on master.

**Comment by traviskaufman** [comment]
Er, dunno why I said `mdc-slider`...probably that's because that's what I was working on last week and I was just really wrapped up in it 😅 

I meant `packages/mdc-toolbar/README.md` (updated the previous comment as well). Specifically [this section](https://github.com/material-components/material-components-web/tree/master/packages/mdc-toolbar#adapter).

**Comment by griest024** [comment]
@traviskaufman does that look good?

**Comment by griest024** [comment]
@traviskaufman I believe I have resolved the conflicts appropriately.

**Comment by traviskaufman** [comment]
@griest024 looks like there aren't any conflicts. If/when CI goes green I'll merge

**Comment by griest024** [comment]
@traviskaufman okay well for reference in case there is an issue there were conflicts with [this line](https://github.com/material-components/material-components-web/commit/f0ff94deb7ff3b0f3076a80e21c16bf2a474c5c3#diff-0a9a27307fa59ac93cb75935a40ef5a8R171) and [this one](https://github.com/material-components/material-components-web/commit/f0ff94deb7ff3b0f3076a80e21c16bf2a474c5c3#diff-0a9a27307fa59ac93cb75935a40ef5a8R172).

The commits on master were renaming `scrollThesholdRatio` to `scrollThresholdRatio` and my commits were renaming `flexibleRowMaxRatio` to `firstRowMaxRatio`.

The PR that this one conflicted with is #764.

**Comment by griest024** [comment]
@traviskaufman [failed](https://travis-ci.org/material-components/material-components-web/jobs/239751562#L1606)

**Comment by traviskaufman** [comment]
Yeah, but it looks like a flake. Passed on node stable but failed on LTS due to browser timeout. 🤷‍♂️ merging anyway.

**Comment by traviskaufman** [comment]
Ah yeah now I'm seeing the conflicts. Could you resolve?

**Comment by traviskaufman** [comment]
I have to sign off for the night but I"ll merge first thing tomorrow.

**Comment by griest024** [comment]
@traviskaufman resolved

**Pull request merged**
