### PR TITLE
fix(ripple): Use mdc-dom.matches everywhere instead of a custom one (#4340)

### LINKED ISSUE #4340: Update ripple and tab-scroller to use mdc-dom/ponyfill.matches
We added an `mdc-dom` package with a common `matches` function, but we still have 2 packages using their own version: Ripple and Tab Scroller.

Additionally, these packages use a version which is run eagerly ahead-of-time, which poses problems in SSR scenarios. (See https://github.com/material-components/material-components-web-react/issues/654)

**Edit:** Only Ripple actually runs the function eagerly, although both work in the same manner.

We should update these components to use `mdc-dom` and remove the duplicate functions.

### PR DESCRIPTION
**Pull request by julien1619**
Fixes #4340

`mdc-dom` implements a `matches()` method that wasn't used everywhere. These custom implementations prevented some SSR usage of the material-components library. This commit removes all the custom implementations.

I removed some tests that were testing a now removed method, and I handled to make the other pass.

PS: This is my first contribution here, I hope I did everything right!

BREAKING CHANGE: `getMatchesProperty()` has been removed from `@material/ripple/util`. Use `matches()` from `@material/dom/ponyfill` instead.

### CODE REVIEW

**Comment by julien1619** [comment]
I've signed the CLA.

**Comment by kfranqueiro** [comment]
Thanks for working on this! However, FYI, we're in the midst of converting all of our modules to TypeScript on the `feat/typescript` branch and we've already converted quite a few of these files. It might be worth waiting for all affected files to be converted and then applying these changes to the TypeScript modules instead... (in particular we haven't converted the tab packages yet)

Sorry for the inconvenience/timing!

**Comment by julien1619** [comment]
No problem! I'll adapt my PR when it's ready. Do you know when you plan to merge the typescript version?

**Comment by kfranqueiro** [comment]
We're aiming for merging the typescript branch into master sometime during March so that it'll be available in the minor release in April.

**Comment by kfranqueiro** [comment]
To clarify, it turns out Andy already made equivalent changes to this on the TypeScript branch, so we're going to go ahead and take this PR for purposes of being able to resolve #4340 in a release without waiting for the TypeScript conversion to land.

**Comment by julien1619** [comment]
Great! Can't wait to see the next release ;)

**Pull request merged**
