### PR TITLE
docs: Add Aurelia wrappers link

### PR DESCRIPTION
**Pull request by MaximBalaganskiy**

### CODE REVIEW

**Comment by asyncLiz** [comment]
Congratulations on creating a wrapper framework for MDC and Aurelia! It's a lot of hard work, and your library and demos are looking top notch 🎉

Keep in mind that one of the [required criteria](https://github.com/material-components/material-components-web/blob/master/docs/integrating-into-frameworks.md) for us to feature a wrapper library is time:

> Have existed for longer than 6 weeks and show continued maintenance over time

At the time of writing, `@aurelia-mdc-web/*` 1.0.0 was published 8 days ago and has two primary contributors. It's a great launch, though I think a little more time is needed to let the library establish itself and stick the landing to meet that third criteria.

**Comment by MaximBalaganskiy** [comment]
Ah, sure... I was just counting the "alpha" time towards these 6 weeks. Will submit later then.

**Comment by asyncLiz** [comment]
It's met the "existence" criteria when considering time in alpha, but the "show continued maintenance over time" is more subjective.

I'll bring this up at our weekly meeting so we can take a deeper dive into defining what that criteria is 🙂

**Comment by MaximBalaganskiy** [comment]
Do we qualify now? :)

**Comment by asyncLiz** [comment]
Thanks for the PR! At the moment our team does not believe adding a link will be useful given our current strategy.

**Comment by MaximBalaganskiy** [comment]
Could you please elaborate a bit on what the current strategy is?

**Comment by asyncLiz** [comment]
We are encouraging new projects to look toward [Material Web Components](https://github.com/material-components/material-components-web-components/) as the exciting future direction of Material on the web. At the moment we'd like to hold off on promoting new wrapper libraries of MDC while we focus efforts on the web component project.

**Comment by MaximBalaganskiy** [comment]
Unfortunately, this is not clearly stated neither on the main page nor in integration docs.
Will foundation classes be still available/supported in the future or MWC is going to be the only way?

**Comment by asyncLiz** [comment]
We're in the middle of planning and discussion, and we don't have any information to share yet, which is why we're holding off on PRs for new libraries. Once we have more details and a roadmap, that will be shared!

**Pull request closed without merging**
