### PR TITLE
feat(infrastructure): add es6 module support

### PR DESCRIPTION
**Pull request by moog16**
fixes https://github.com/material-components/material-components-web/issues/4722

This now builds ES6 with ESModule import/export syntax. These files will be found within each package under the `packages/mdc-foo/es6` directory.

@abhiomkar I think we may want to add some verification check like we have with `scripts/verify-pkg-main.js`. If you want me to add to this let me know and I can modify it.

### CODE REVIEW

**Comment by rarous** [comment]
@moog16 thank you for working on this. If I'm reading correctly your changes, there is still missing one thing to work it correctly and it is [`es2015` entry in `package.json`](https://2ality.com/2017/04/setting-up-multi-platform-packages.html#es2015%3A-es6%2C-esm) pointing to ES2015 module.

**Comment by moog16** [comment]
@rarous is that actually a package.json entry? I can't find the webpack/rollup documentation for `es2015` on either of their sites. This leads me to believe that this isn't a real package.json property. We currently have `module`, however this is already taken.

One of the main objectives of this PR is to not break anyone but add functionality.

**Comment by rarous** [comment]
@moog16 Most of the tooling has this configurable. But it should be in `package.json`. My suggestion is to use `es2015` or to use `module` and introduce `browser` for current `module` entry.

**Comment by moog16** [comment]
Can you provide some kind of documentation besides Dr Axel's blog? I respect him and his work, but I would something more official?

**Comment by rarous** [comment]
@moog16 There really no standard for this, best resource I can get is this https://github.com/stereobooster/package.json#package-bundlers.

**Comment by abhiomkar** [comment]
Closing this as obsolete. 

If we're going to introduce ES6 syntax in modules it would the only syntax. Replace existing module which is transpiled to ES5.

**Pull request closed without merging**
