### PR TITLE
fix(data-table): change svg attribute name viewbox to viewBox (#5483)

### PR DESCRIPTION
**Pull request by jony666666**

### CODE REVIEW

**Comment by asyncLiz** [comment]
@jony666666 any update on adding the fix for the other instance of this typo?

**Comment by jony666666** [comment]
> @jony666666 any update on adding the fix for the other instance of this typo?

I searched the whole project code and didn't find the other instance of this typo.

**Comment by jony666666** [comment]
> Thanks for the PR! Can you also update [component.ts:51](https://github.com/material-components/material-components-web/blob/master/packages/mdc-data-table/test/component.test.ts#L51)?

I created a new PR for it. I don't have much experience of using Github,I don't know if this is a good way.

**Comment by asyncLiz** [comment]
No worries @jony666666, it actually looks like you updated this PR as well.

For the future, all you need to do is create a new commit with more changes and push it to your branch. The PR will automatically update. 😊

**Comment by jony666666** [comment]
> No worries @jony666666, it actually looks like you updated this PR as well.
> 
> For the future, all you need to do is create a new commit with more changes and push it to your branch. The PR will automatically update. 😊

ok , thank you!

**Pull request merged**
