### PR TITLE
style: add left and right margin to helptext

### LINKED ISSUE #1009: style/mdc-textfield--box
## Style improvement

I came across an inconsistency with the newly added text field boxes, specifically with its helper text. The helper text should have a left and right margin of 16 pixels. 

### What MDC-Web Version are you using?

0.16

### What browser(s) is this bug affecting?

all

### What OS are you using?

Windows 10 Enterprise (14393)

### What are the steps to reproduce the bug?

Click in the text field box that is required and then blur the input by clicking outside. The help text appears (as an error) and it is allgned to the left with no margins. 

### What is the expected behavior?

It should follow the MD Guidelines for text field boxes found [here](https://material.io/guidelines/components/text-fields.html#text-fields-text-field-boxes)

### What is the actual behavior?

It is left alligned with no margins

### Any other information you believe would be useful?

Creating a pull request.

### PR DESCRIPTION
**Pull request by MrGrigri**
style: add left and right margin to helptext

add left and right margin of 16 pixels for helper text of mdc-textfield--box css class

closes #1009

### CODE REVIEW

**Comment by MrGrigri** [comment]
I'm not quite sure why this is failing. Does anyone have any idea?

**Comment by amsheehan** [comment]
@MrGrigri looks like our linter is complaining about the change

screen shot 2017-07-26 at 12 43 29 pm

You shouldn't have to use this pattern to select on `help text` for `mdc-textfield--box`. This should suffice:

```css
.mdc-textfield--box {

  ...

  .mdc-textfield-helptext {
    margin-right: 16px;
    margin-left: 16px;
  }

  ...

}
```

You'll find `.mdc-textfield--box` around line 129 in `mdc-textfield.scss`

**Comment by MrGrigri** [comment]
the `.mdc-textfield-helptext` is a sibling and not a child of `.mdc-textfield--box`. So that wouldn't work. If you look at lines 315 to 320 [here](https://github.com/MrGrigri/material-components-web/blob/d7d06071acc051f1c23476c73cffe641b3b55665/packages/mdc-textfield/mdc-textfield.scss#L315-L320)) you'll see that this is the same selector.

**Comment by MrGrigri** [comment]
@amsheehan I've fixed the build issue. Can I get a code review with this?

**Comment by amsheehan** [comment]
@MrGrigri Sure thing. Updating the branch and I'll give it a look. Thanks!

**Pull request merged**
