### PR TITLE
fix(text-field): Clicking label should focus textfield

### PR DESCRIPTION
**Pull request by williamernest**
Fixes : #2015 
Makes the label work like a standard label. If the `for` attribute is specified, clicking the label will focus the corresponding `input`.

### CODE REVIEW

**Comment by kfranqueiro** [comment]
FYI this will probably make press ripples seem flaky but we're planning to remove that from text field anyway; I had neglected to file an issue before but I just entered #2354 now.

**Comment by williamernest** [comment]
I don't think they're flaky. There's really no discernible difference that I can tell other than clicking the top half of the outlined label doesn't cause a ripple. It behaves the same way that tabbing into the field does.

**Comment by kfranqueiro** [comment]
Huh. I was thinking the label would block the input (which the ripple listens on) from receiving pointer events since it's a sibling, but I guess it doesn't?

**Comment by williamernest** [comment]
The original click event isn't blocked by the label.

**Comment by moog16** [comment]
Yes I can confirm that behavior, which also works on FF. After chatting with Will, that behavior isn't documented in the HTML spec. Change looks good to me.

**Pull request merged**
