### PR TITLE
fix(toolbar): Correct class name for mdc-toolbar-fixed-adjust

### LINKED ISSUE #320: Incorrect class name used for mdc-toolbar-fixed-adjust
### What MDC-Web Version are you using?

v0.5.0

### What browser(s) is this bug affecting?

Every.

### What OS are you using?

4.9.9-1-ARCH

### What are the steps to reproduce the bug?

Follow the [fixed toolbar documentation](https://github.com/material-components/material-components-web/tree/master/packages/mdc-toolbar#fixed-toolbars).

### What is the expected behavior?

Add top margin to the siblings of the fixed toolbar.

### What is the actual behavior?

No added margin caused by two typos in the documentation.

### Any other information you believe would be useful?

I can quickly provide a pull request to fix this.

### PR DESCRIPTION
**Pull request by zeromalist**
Fixes #320

### CODE REVIEW

**Comment by zeromalist** [comment]
Yes, my bad. Done!

**Comment by traviskaufman** [comment]
@zeromalist if you move the `// postcss-bem-linter: end` to a line before `.mdc-toolbar-fixed-adjust` is defined, it should stop the linter from failing. You can verify this by running `npm run lint:css` locally (assuming you've already run `npm install`).

**Comment by zeromalist** [comment]
Passes now. Thanks for hint. Still learning.

**Comment by traviskaufman** [comment]
Patched and released on npm as mdc-toolbar@0.1.1

**Pull request merged**
