### PR TITLE
feat(toolbar): add `pointer` for `icon` element

### PR DESCRIPTION
**Pull request by Shyam-Chen**

### CODE REVIEW

**Comment by Shyam-Chen** [comment]
done.

**Comment by Garbee** [comment]
This seems icky to me. The *icons* shouldn't trigger anything. In fact they should be `pointer-events: none` so they don't trigger any events in JS or anything in-accurately. It is the underlying buttons that should have the hover triggers and event listeners if any are to exist.

**Comment by yeelan0319** [comment]
@Garbee Curious about your suggestion here "icon shouldn't trigger anything. It is the underlying buttons that should have the hover triggers". Does this means a button need to be nested within `&__icon` if the icon is intended to have an action? Such as:
```
<header class="mdc-toolbar mdc-toolbar--fixed">
  <div class="mdc-toolbar__row">
    <div class="mdc-toolbar__icon" aria-label="Download" alt="Download">
      <button><i class="material-icons">file_download</i></button>
    </div>
  </div>
</header>
```

IMHO, this makes toolbar structure bulkier than it is but the gain here is pretty limited, since based on the [guideline](https://material.io/guidelines/layout/structure.html#structure-app-bar) that all the icons within toolbar should be actionable. Correct me if I get your meaning wrong.

**Comment by Garbee** [comment]
Ah, I see now looking at the code more. The class naming changed some from what we were initially demoing for the component early on. This LGTM knowing that.

**Comment by yeelan0319** [comment]
Yeah, there were some other issues related to those icons so we renamed it.
I saw you filed a couple of issues regarding the naming, let's triage them later on.

**Pull request merged**
