### PR TITLE
docs: Updated getting started guide with webpack fix

### PR DESCRIPTION
**Pull request by MrSimmmons**
- Fixed getting started quite to support the latest webpack changes
- Updated some code consistency

### CODE REVIEW

**Review by brandondiamond — CHANGES_REQUESTED** [review]
Thanks for putting this together! Before we merge, could you share a test repo to verify that the docs are generated as expected by setup and everything looks reasonable? Thank you!

**Comment by CyborgSemon** [comment]
@brandondiamond https://github.com/CyborgSemon/material-components-guide-test
`npm i && npm start`

**Comment by CyborgSemon** [comment]
One thing that I did find a little strange is why `darkslamon` is the colour of choice for the button customisation example. Since I was just copy pasting the getting stated code, I didint see that `darkslamon` was in there so when the dev server started up and the button had different colours to the [button](https://github.com/material-components/material-components-web/blob/master/docs/button.png) and [button with ripple](https://github.com/material-components/material-components-web/blob/master/docs/button_with_ripple.png) images, I thought something was broken.
So maybe that should be changed as well? Idk

**Comment by CyborgSemon** [comment]
Also, I have no idea why those github tests have failed. All I changed was the markdown file

**Comment by anlexN** [comment]
can we solve PR?

**Comment by MrSimmmons** [comment]
Very outdated at this point. Closing

**Pull request closed without merging**
