### PR TITLE
Fix typo in mdc-menu

### PR DESCRIPTION
**Pull request by nevi-me**
There was a small error in the JS snippet

### CODE REVIEW

**Comment by nevi-me** [comment]
@googlebot I signed it

**Comment by sgomes** [comment]
Thanks for the PR, @nevi-me!

Any chance you could change the commit message to `fix(menu): Update MDCMenu README.md` to fit our commit naming conventions? Thanks!

**Comment by sgomes** [comment]
Actually, I think I can do that myself. Let me give it a try.

**Comment by sgomes** [comment]
Done! Thanks again, @nevi-me!

**Pull request merged**
