### PR TITLE
fix(toolbar): Wrong placement of last icon when there is a menu

### LINKED ISSUE #1026: Toolbar: Wrong placement of last icon when there is a menu
### What MDC-Web Version are you using?

> 0.16.0

### What browser(s) is this bug affecting?

> All browsers

### What OS are you using?

> Windows 7

### What are the steps to reproduce the bug?

> 1. Have a toolbar [like here](http://material-components-web.appspot.com/toolbar/default-toolbar.html)
> 2. Add a simple menu to the most right icon
> 3. Observe the right padding (placement) of the last icon

### What is the expected behavior?

> It should have a `padding-right: 16px;`

### What is the actual behavior?

> It has a `padding-right: 8px;` (like normal icons)

### Any other information you believe would be useful?

> This is caused by `mdc-toolbar__icon:last-child`. The toolbar icon isn't the last child because there is a simple menu after it. A simple fix would be to use `last-of-type` instead of `last-child`.
Would you like a PR to fix this?

### PR DESCRIPTION
**Pull request by touficbatache**
Fixes and closes #1026 @yeelan0319

### CODE REVIEW

**Comment by kfranqueiro** [comment]
Should we have an example of this added to the toolbar demos?  Maybe addressable separately but IIUC there's nothing OOTB that demonstrates the issue/fix right now.

**Comment by touficbatache** [comment]
I can do that, so from what I unrderstood I should add an example with the menu, correct?

**Comment by kfranqueiro** [comment]
Yes, specifically what I had in mind was add another example to the toolbar demos that contains a menu on the last icon.  It should then be easy to test with/without the CSS change to see the fix.

**Comment by touficbatache** [comment]
I made the necessary changes! @yeelan0319 @kfranqueiro

**Pull request merged**
