### PR TITLE
fix(dialog): Increase z-index above Drawer

### LINKED ISSUE #3596: Drawer z-index causes it to overlap dialogs
When MDC Drawer was updated, its z-index changed:

* It was raised from 5 to 6
* It is now applied to _all_ drawer variants, whereas it used to only be applied to temporary (modal)

Meanwhile, Dialog currently has a z-index of 5.

So I have the following questions:

* Why was the z-index of drawer increased?
* Does it really need to be applied to all variants? (I suspect it does need to be applied to dismissable, which means there's still the potential for conflict with Dialog)

I suspect we might not need to raise Dialog's z-index, if it's feasible for Drawer to be restored to 5, since dialogs are most likely to come after drawers in the DOM, but if we want to be safe we should raise Dialog's as well.

### PR DESCRIPTION
**Pull request by kfranqueiro**
Fixes #3596.

Also adds a screenshot test page.

Before:
before

After:
after

### CODE REVIEW

**Comment by amsheehan** [comment]
Does this also put it above top app bars?

**Comment by kfranqueiro** [comment]
Yes. See https://github.com/material-components/material-components-web/issues/3596#issuecomment-423288588

**Comment by kfranqueiro** [comment]
Now I'm actually wondering something...

Why is drawer unconditionally above top app bar? Shouldn't that only be necessary for modal drawer? Should other drawer variants actually be _lower_ to support the drawer being clipped by the top app bar? (which would avoid the issue in dialog entirely since modal drawer and modal dialog should never be open at the same time)?

cc @abhiomkar

**Comment by abhiomkar** [comment]
We need the drawer on top of TopAppBar for Dismissible variant where it slides over it on close. So it is intended to be always on top of TopAppBar.

**Pull request merged**
