### PR TITLE
fix(demos): Fix non-unique ids in radio demo

### PR DESCRIPTION
**Pull request by jscissr**
Previously, the first set of radios would change when clicking the labels of the disabled radios.

https://material-components-web.appspot.com/radio.html

### CODE REVIEW

**Comment by jscissr** [comment]
Just found another one: In https://material-components-web.appspot.com/switch.html the first 'off/on' label changes the centered toggle

**Comment by traviskaufman** [comment]
@jscissr Thanks for helping us track these down. Feel free to submit a separate PR for that one, or just roll it into here.

**Comment by traviskaufman** [comment]
@jscissr going to merge this in. Feel free to open another PR for switches and thanks again!

**Comment by jscissr** [comment]
I see now the other bug was already fixed in #747, the demo page just hasn't been updated yet.

**Pull request merged**
