### PR TITLE
fix(top-app-bar): reopen short top-app-bar

### LINKED ISSUE #4928: TopAppBar short never reopens after initial scroll
### Steps to reproduce
1. Go to https://material.io/develop/web/components/top-app-bar/
2. Scroll down to the "short" variant of the top-app-bar
3. Scroll down, notice it shrinks
4. Scroll back to top, notice it does not restore to its original full size

### Expected behavior
The top-app-bar should restore to its original size for the short variant whenever the page is scrolled back to the top

Noticed this while upgrading RMWC to 3.0.0. I don't believe this was an issue with 2.0.0

### PR DESCRIPTION
**Pull request by TroyTae**
moved from #4995
fixes #4928

### CODE REVIEW

**Comment by azakus** [comment]
This will break the always-collapsed variant after the first scroll, as the state changes are:
```
init:
isCollapsed?: no
remove class?: no

scroll down:
isCollapsed?: yes
add class?: yes

scroll up to top:
isCollapsed?: yes
remove class?: yes
```

The foundation needs a setter to skip the scroll handling if the bar should always be collapsed.

**Comment by TroyTae** [comment]
@azkkus
Thank you!
And it seems you already create another PR.
I’ll close this :)

**Comment by azakus** [comment]
@TroyTae I think you should take the `top` => `translate` change from this PR and make a new PR. Probably still a good idea :)

**Comment by TroyTae** [comment]
@azakus 
Cool!
I'll create a new PR, after your code is merged :)

**Pull request closed without merging**
