### PR TITLE
feat(ripple): export util from @material/ripple

### PR DESCRIPTION
**Pull request by Kerrick**
[The docs recommend](https://material.io/components/web/catalog/ripples/#using-the-foundation) using certain functions from util when implementing an adapter for the ripple foundation. It is not currently possible to `import { util } from '@material/ripple';`, even though this pattern is [established](https://github.com/material-components/material-components-web/blob/92aab2b2dffaa9d31ce99d68322dcce90dcffc0a/packages/mdc-toolbar/index.js#L23) in `mdc-toolbar`.

### CODE REVIEW

**Comment by anton-kachurin** [comment]
Related issue is #253. It also mentions that docs for ripple need to be expanded.

**Comment by lynnjepsen** [comment]
Actually, I approved a little too quickly...could you also add documentation to the README? And put Resolves #253: in the body of the commit.

**Comment by Kerrick** [comment]
The docs already say the following under **Using the foundation**:

> We provide a `supportsCssVariables` function within the `util.js` which we recommend using, as it handles this for you.

What more should I document about it?

Also, should I add an example to the ES2015 etc. imports (example below)? Was wondering about that since it's under **Adding the ripple JS** rather than **Using the foundation**.

```js
import {MDCRipple, MDCRippleFoundation, util} from '@material/ripple';
```

I'll be glad to make the requested changes once I'm a bit clearer on what's best. :+1:

**Comment by lynnjepsen** [comment]
Mdc-drawer has a good example of documenting **The util API**

https://github.com/material-components/material-components-web/tree/master/packages/mdc-drawer

Mdc-ripple README should document 
- supportsCssVariables
- applyPassive
- getMatchesProperty
- getNormalizedEventCoords

And, again using mdc-drawer as an example, looks like you should add 

`import {MDCRipple, MDCRippleFoundation, util} from '@material/ripple';`

Thank you!

**Comment by yeelan0319** [comment]
Hi @Kerrick, trying to loop back to see if there is any updates :)

Let us know if there is anything you need us help for clarification.

**Comment by Kerrick** [comment]
Whoops, sorry about that! Got caught up in a big product launch at work and lost track. Should be able to get these changes back to you shortly.

**Comment by Kerrick** [comment]
I've pushed the requested changes :+1:

**Pull request merged**
