### PR TITLE
feat: Add index stylesheets to mdc-image-list and mdc-layout-grid.

### PR DESCRIPTION
**Pull request by nex3**
Adds indexes to GitHub-only stylesheets that aren't covered by material-components/material-components-web#5539.

### CODE REVIEW

**Comment by nex3** [comment]
Looks like that did it :woman_shrugging:.

**Comment by abhiomkar** [comment]
@nex3 Any idea why Sass was not able to resolve module when `@import` statement is used?

Material Web Components (MWC) is still using `@import` statements and it [broke](https://github.com/material-components/material-components-web-components/pull/817/checks?check_run_id=418055874) their Sass build.

/cc @e111077 @dfreedm

**Comment by trimox** [comment]
@abhiomkar I may have stumbled on similar issue upgrading Angular MDC to v5.0-canary branch. If a component package folder contains `index.ts` along with `_index.scss` the build fails.

Works successfully with `@use '@material/checkbox/_index' as checkbox;`

Fails to compile using `@use '@material/checkbox';` or `@use '@material/checkbox' as checkbox;`
image

**Comment by nex3** [comment]
Does anyone have a reproduction that just uses the command-line Sass compiler, so I can debug into it and see what's going wrong here?

**Comment by abhiomkar** [comment]
I surely looks like `sass-loader` bug when handling index file.

I'm able to reproduce only with sass-loader (Webpack Sass plugin):
https://github.com/abhiomkar/sass-module-bug

**Comment by abhiomkar** [comment]
Created [bug](https://github.com/webpack-contrib/sass-loader/issues/804) with sass-loader.

**Pull request merged**
