### PR TITLE
fix(ripple): Correct unbounded ripple diameter

### LINKED ISSUE #1067: Correct unbounded ripple diameter
### What MDC-Web Version are you using?

> 0.16.0

### What browser(s) is this bug affecting?

> All browsers (Chrome newest)

### What OS are you using?

> All OS (Windows 7, Android 7)

### What are the steps to reproduce the bug?

> 1. Add a ripple to the toolbar icons
> 2. Observe the component's behavior
>
> https://codepen.io/anon/pen/YxGLQE

### What is the expected behavior?

> The ripple should be close to the size of the icon.

### What is the actual behavior?

> The ripple is a lot bigger than what it should be.

### PR DESCRIPTION
**Pull request by touficbatache**
Finally fixes and closes #1067! :smiley:
What do you think @lynnjepsen @kfranqueiro @yeelan0319? Tell me if you want anything changed! I'll add the tests later on (could anyone help with that?)

### CODE REVIEW

**Comment by touficbatache** [comment]
Anyone? @lynnjepsen @kfranqueiro @yeelan0319

**Comment by touficbatache** [comment]
It's been nearly a month... Could anyone help review this PR? @kfranqueiro

**Comment by lynnjepsen** [comment]
hey @touficbatache, seems like you're trying to do two things in this PR:
1) Update the toolbar demo to show a ripple on toolbar's icon buttons
2) change the unbounded ripple

Can you split out the toolbar demo code into a new PR? 

And for the unbounded ripple...honestly it might be very difficult for you to accomplish this remotely. We have to work super closely with our designers to figure out the specifics of @kfranqueiro is going to take a stab at this soon, so maybe you could just be on the look out for that PR and comment on it?

Thanks again for the enthusiasm toufic...ripple is just so tricky we tend to go through very intense code review.

I'm going to close this PR, but feel free to open a new one with the toolbar demo code changes.

**Comment by touficbatache** [comment]
Hey @lynnjepsen, I made the toolbar changes because without them, the new ripple wouldn't work. The old ripple looks very bad on toolbar icons without this PR so I'm not going to open another one.

For the ripple, I would be willing to work with @kfranqueiro to find a solution.

Thanks!

**Pull request closed without merging**
