### PR TITLE
Add React Material Design as Seamless Library

### PR DESCRIPTION
**Pull request by miguel-orange**
[GitHub](https://github.com/react-material-design/react-material-design)
[NPM](https://www.npmjs.com/package/react-material-design)
[Website](https://reactmaterial.com)

Library meets the criteria:
* Serve components in an à-la-carte delivery model
* Have existed for longer than 6 weeks and show continued maintenance over time
* Provide usage documentation per component

### CODE REVIEW

**Comment by miguel-orange** [comment]
I signed it!

**Comment by miguel-orange** [comment]
I'm not sure that travis failed due to my README.md changes. Let me know is there's anything I can do to get that build to pass.

**Comment by miguel-orange** [comment]
@lynnjepsen, Hello. How do I get this change reviewed/approved?

**Comment by moog16** [comment]
@miguel-orange thanks for submitting the PR. I took a look at your PR and I have a few comments:

1. Can you explain why you chose glamorous? I think it adds a second layer of complexity when trying to integrate your components into another site. I not only have to learn MDC API, but also Glamorous' API. 
1. There are some missing docs. For example, <Switch /> or <Radio />.
1. Docs would be better with the API clearly stated. As a developer it would be a lot easier to see this in a README on Github to see what hooks I have into the component instead of combing through the code. 
1. Call `mdcComponent.destroy()` on componentWillUnmount(). This is a memory leak if you don't remove unmounted components.
1. Not clear to me how to hook into React event listeners, such as onClick, onChange, etc. For example for <Switch /> and <Radio />, how should a developer use that input to update React State/Props? 

Going to close for now. When you address some of the comments and changes you can reopen.

**Pull request closed without merging**
