### PR TITLE
fix(dialog): Layout footer buttons' ripples after open transition ends

### LINKED ISSUE #464: Ripples incorrectly laid out for dialog buttons
### What MDC-Web Version are you using?

0.8.0

### What browser(s) is this bug affecting?

Tested on Chrome Version 57.0.2987.133 (64-bit)

### What OS are you using?

macOS v10.12.3

### What are the steps to reproduce the bug?

1. Navigate to http://material-components-web.appspot.com/dialog.html
1. Click the "Show Dialog" button
1. Press and hold the spacebar key, observing the ripple on the accept button as you do so

### What is the expected behavior?

The ripple should cover the entirety of the button

### What is the actual behavior?

The ripple is sized incorrectly and placed incorrectly within the dialog.

### Any other information you believe would be useful?

If you open a dialog and then resize the screen, even a little bit, the ripple becomes positioned and sized correctly. This leads me to believe that _this is an issue with when the ripple is being laid out_. 

I think that a solution might be to call `layout()` on all of the ripple instances after the dialog opens. However, this presents an issue since the `layout()` method is not exposed at the `MDCRipple` component level. Perhaps this is something we should look into in order to accomplish this.

### PR DESCRIPTION
**Pull request by kfranqueiro**
BREAKING CHANGE: Adds a new adapter method, `layoutFooterRipples`, to allow the foundation to
communicate with ripples when the dialog's opening transition ends.

Fixes #464.

### CODE REVIEW

**Comment by kfranqueiro** [comment]
Alex realized that the reason codecov detected decreased coverage is because I'm testing the foundation but not specifically the new calls to MDCRipple#layout.  I'll have to see if I can make a component test to do that.

**Comment by touficbatache** [comment]
Is this being worked on? @amsheehan @kfranqueiro

**Comment by kfranqueiro** [comment]
Hey @touficbatache, thanks for checking in; sorry I hadn't gotten back to this as quickly as I'd hoped, but I'm still hoping to get this sorted out this week.

**Comment by kfranqueiro** [comment]
I added a commit which adds a component test that stubs `MDCRipple#layout` in order to verify the default adapter calls it. However, I had to disable the `mocha/no-hooks` rule in order to do this, since I have to stub a prototype-level method, which means I need to be sure to tear it down properly lest the stubbed method hang around and affect other tests. I'm willing to discuss alternate approaches, but I'm also inclined to think that sometimes a proper `after` or `afterEach` is necessary in tests.

**Pull request merged**
