### PR TITLE
Fixed the import location for the style.

### PR DESCRIPTION
**Pull request by hilljh82**

### CODE REVIEW

**Comment by hilljh82** [comment]
Done! It was submitted as my company under james@onehilltech.com <mailto:james@onehilltech.com>

**Comment by williamernest** [comment]
@hilljh82 It looks like that's not linked to your github account or the CLA bot is having trouble linking them. If could double check it's signed with your github account and then post `I signed it!` in this PR I can merge this.

**Comment by hilljh82** [comment]
I signed it!

**Comment by kfranqueiro** [comment]
We're still unable to merge this since the CLA check is failing. Can you amend the commit in the branch to match your CLA e-mail? (Or just close this and send a new commit against current master after configuring `user.email` in your checkout's git config, if that's easier?)

**Comment by kfranqueiro** [comment]
Since it looks like you were able to fix your config for your other PR, would you like to do the same for this one?

**Comment by kfranqueiro** [comment]
I'm overriding the CLA check since this is a straightforward docs fix and we've merged at least one PR from you which did pass the CLA.

**Pull request merged**
