### PR TITLE
feat(expansion-panel): Add Expansion Panel component

### LINKED ISSUE #46: Investigate making Expansion Panel
Spec reference: https://www.google.com/design/spec/components/expansion-panels.html

- [ ] Single Expansion Panel
- [ ] Expansion panel group / accordion (a la Inbox)

> Copied from https://github.com/google/material-design-lite/issues/4499

### PR DESCRIPTION
**Pull request by griest024**
closes #46

This is ready for code review.

[Engineering Outline](https://docs.google.com/document/d/1y0092LZJABV-T2_dKX4THlwb7l9j8-zg3yh5J4uWTko/edit?usp=sharing)

TODO:

- [x] Accordion
- [x] Block `toggleExpansion()` when target is not appropriate
- [x] Docs/README
- [x] RTL
- [x] Theming
- [ ] Accessibility
- [x] Tests
- [x] SCSS mixins and partials
- [x] ~~Define keyframes~~
- [x] Tab key selection
- [ ] No JS variant
- [x] Closure compatibility

I need guidance on a few things:

- I set the inner HTML of the expansion icon(s) to `expand_more` in the foundation because the spec shows that exact icon. Is this preferable to actually inserting the icon into the header manually and not having the user create the icon at all?
- The spec doesn't say how to style the text in the body or footer sections. Should I use the "Label" text style (15sp Roboto Regular; 87% black)?
- The theming is still a bit weak. With dark theme going away, what is the proper way to implement component theming in a dark context?

### CODE REVIEW

**Comment by touficbatache** [comment]
Hey!

Your implementation of the expansion panel is very good and it matches the guidelines really well. However, you might need to change some things so it perfectly matches with the guidelines:

- [ ] Change `padding: 16px 0 16px 24px;` to `padding: 16px 8px 16px 24px;` in `.mdc-expansion-panel .mdc-expansion-panel__footer`.

- [ ] The `text-secondary` class should have the same font-size as `mdc-expansion-panel__summary`. And maybe change its class to `mdc-expansion-panel__text-secondary` or something in that kind?

- [ ] We should be able to change the secondary text in the expanded view because nothing is mentioned in the guidelines that says otherwise.

Thank you for your help!

**Comment by griest024** [comment]
@touficbatache

> We should be able to change the secondary text in the expanded view because nothing is mentioned in the guidelines that says otherwise.

You can, just mark an element with `...__summary` or `...__details` to make it specific to the state of the panel. The demo is not thorough yet.

>  Change padding: 16px 0 16px 24px; to padding: 16px 8px 16px 24px; in .mdc-expansion-panel .mdc-expansion-panel__footer. Remove the margin: 0 8px 0 0; and padding: 0; from the .mdc-expansion-panel .mdc-expansion-panel__footer .mdc-expansion-panel__footer__button-bar button element.

Thanks this is better.

>  The text-secondary class should have the same font-size as mdc-expansion-panel__summary (in your case 15px, I'm not sure if it's the correct size...). And maybe change its class to mdc-expansion-panel__text-secondary or something in that kind?

Yes I think I misunderstood the purpose of secondary text. The spec is vague about all the different opacities of the various texts they show.

> Add a small transition.

[It's already there](https://github.com/material-components/material-components-web/pull/2020/files#diff-484444401e7abe582bdd09e8563cbd2fR33). I suppose its not very obvious in the codepen demo. You should check out this branch and run the dev server. I have the demo all set up.

**Comment by griest024** [comment]
It would be great if you could merge #2118 first as my test results list and code coverage is funky without the correct suite identifiers.

**Comment by griest024** [comment]
@lynnjepsen Can someone review this? I would love to see this in the next release.

**Comment by touficbatache** [comment]
@lynnjepsen @acdvorak @kfranqueiro Can anyone of you guys help with this? Thanks!

**Comment by griest024** [comment]
Can someone please review this? Its almost a month old.

**Comment by touficbatache** [comment]
I suggest you build your own version of MDC-Web and use it in your projects
until they review this!

**Comment by kfranqueiro** [comment]
Thanks for spending time on this, and sorry we haven't gotten a chance to review it yet. We want to give this PR the full attention it deserves, but we're aiming to finish ongoing work on some of the other components we've been plugging away at first.

Sorry again for the delay, and thanks for your patience and hard work!

**Comment by touficbatache** [comment]
It's been 3 months!! Is anyone trying to work on this? @kfranqueiro

**Comment by touficbatache** [comment]
Hey @moog16 @kfranqueiro, what's up with that?

**Comment by bmitchinson** [comment]
@kfranqueiro @moog16 Using this in our upcoming project, thank you @griest024 for your awesome work! The sooner this is implemented, the sooner RMWC can make a wrapper, so please give us an update?

**Comment by moog16** [comment]
@touficbatache first time I'm seeing this PR. I would review it, but unfortunately it is not in spec any longer. I'm going to start chatting with designers about what type of guidance they want to provide. The next window is not until after 6/20.

**Comment by touficbatache** [comment]
@moog16 That's weird, I searched the material.io website for expansion panels inside transitions and navigational transitions with no luck.. The best thing is to ask the designers!

**Comment by moog16** [comment]
@touficbatache ya, since I/O and with the release of the new spec a lot of things were changed/removed/etc. But I'll stay on top of this and I added something to my calendar for later this month.

**Comment by moog16** [comment]
@bmitchinson I'm not an expert with RMWC's pattern, but if you wanted to roll your own using our adapter/foundation method there is a Codelab that goes over the basics:

https://codelabs.developers.google.com/codelabs/mdc-112-web/index.html?index=..%2F..%2Findex#0
https://github.com/material-components/material-components-web-codelabs

**Comment by moog16** [comment]
I spoke with design and unfortunately they are not adding it to the spec anytime soon. Because of this we won't be adding expansion panel into the core repo. If you haven't already I suggest forking this repo and adding this PR.

Alternatively design offered this advice as a workaround. Instead of using this component, just use `mdc-list` with a child list within. In code I believe it would look something like:

```
<ul class='mdc-list'>
  <li class='mdc-list__item'>item 1</li>
  <li class='mdc-list__item'>
    <ul class='mdc-list>
      <li class='mdc-list__item>item a</li>
      <li class='mdc-list__item>item b</li>
    </ul>
  </li>
</ul>
```

**Comment by crazyx13th** [comment]
sorry, but example not working... noting happend :-/
grafik

**Comment by robbyrice** [comment]
It looks like you are using hyphens (-) instead of a double underscore (__) in some of the class names. For example `class="mdc-list-item"` should be `class="mdc-list__item"`. Hope this helps.

**Comment by crazyx13th** [comment]
thx for hint, but: nope, no collapse effect ( I try it all before) 
grafik

**Comment by griest024** [comment]
@crazyx13th this PR is insanely old, I'm not surprised that its broken. If there is high demand for it, I might fix it but since the component has been dropped from the spec, I'm basically abondoning this feature.

**Comment by crazyx13th** [comment]
thx for you effort! But I only had interest in the workaround, because at first: you right > dropped from the spec and second: only need for "old layout" from our product. next year maybe it's not inside the new layout.

**Comment by griest024** [comment]
@crazyx13th If I have some free time this weekend, then I'll package this up in its own library or something.

**Comment by jasonsturges** [comment]
As noted in #3738, I wanted to point out here Material Design specifies expand and collapse for Lists:

https://material.io/design/components/lists.html#types

image

**Comment by touficbatache** [comment]
Yess! Thanks for finding that. I also found it in the Play Store, inside the app details page -> Developer Details

**Comment by BlkPingu** [comment]
Was the Accordion merged? I need this badly

**Comment by Misiu** [comment]
The spec is available here: https://material.io/archive/guidelines/components/expansion-panels.html
Should I create a feature request for this?

**Comment by asyncLiz** [comment]
That spec is an archived version of Material, the expansion panel is no longer part of the Material spec. Instead, expanding and collapsing sections are treated as standalone features in certain components, such as lists and data tables.

**Comment by Misiu** [comment]
@asyncLiz I didn't notice that `archived` in the URL 🙈 sorry for that.
So there is no "accordion" component? That's a weird design decision.
Where can I ask for reconsidering? 😏

Anyway, it looks I must search for alternatives or redesign my form.

**Pull request closed without merging**
