### PR TITLE
build: add missing & update package-lock.json on packages

### PR DESCRIPTION
**Pull request by borisdamevin**
- Add missing `package-lock.json` files on most packages.
- Update existing `package-lock.json` files.

### CODE REVIEW

**Comment by asyncLiz** [comment]
Thanks for the PR! At this moment we are not using package-locks per package folder since we use `lerna` to manage them. We do not `npm install` individual packages without bootstrapping everything.

**Comment by borisdamevin** [comment]
Thank your @asyncLiz for this precision. But why some package have `packge-lock.json` and others don't?

**Comment by asyncLiz** [comment]
Good catch! We shouldn't have those there. Would you be willing to open a PR deleting them?

**Comment by borisdamevin** [comment]
@asyncLiz Yes of course, you can find the PR [here](https://github.com/material-components/material-components-web/pull/5697).

**Pull request closed without merging**
