### PR TITLE
fix(slider): value validation and integer comparison

### PR DESCRIPTION
**Pull request by simonziegler**
Fixes issue #7404. PR submitted upon a request from @vkirilyuk in the issue discussion.  It may still be a better quality solution to use a full precision decimal representation for these two integer checks. See [this article for ideas](https://www.avioconsulting.com/blog/overcoming-javascript-numeric-precision-issues)

### CODE REVIEW

**Comment by joyzhong** [comment]
Thanks for the fix! Looks good, but could you also please add a test?
https://github.com/material-components/material-components-web/blob/master/packages/mdc-slider/test/foundation.test.ts

**Comment by simonziegler** [comment]
@joyzhong I'm setting myself a challenge to see if I can but this is way outside my comfort zone. Would it be something similar to [line 42](https://github.com/material-components/material-components-web/blob/master/packages/mdc-slider/test/foundation.test.ts#L42)?

**Comment by joyzhong** [comment]
That's correct, it could be something like https://github.com/material-components/material-components-web/blob/978a3b5bbf8c55fd1c81e09cef6bd3912aed92fe/packages/mdc-slider/test/foundation.test.ts#L186 where you verify that we don't throw an error for certain initial values that would previously have thrown.

**Comment by simonziegler** [comment]
> That's correct, it could be something like
> 
> https://github.com/material-components/material-components-web/blob/978a3b5bbf8c55fd1c81e09cef6bd3912aed92fe/packages/mdc-slider/test/foundation.test.ts#L186
> 
> where you verify that we don't throw an error for certain initial values that would previously have thrown.

Thanks - I hope I got this right in the test code.

**Pull request merged**
