### PR TITLE
fix(select): Selection handler parameter

### PR DESCRIPTION
**Pull request by xxRockOnxx**
Should not destructure.

### CODE REVIEW

**Comment by xxRockOnxx** [comment]
I signed it!

**Comment by yeelan0319** [comment]
Hi @xxRockOnxx ,

I believe the deconstruct is needed. In mdc-simple-menu [README.md](https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/README.md#handling-selection-events), the event data is wrapped inside `detail`. The implementation of the wrapping is in mdc-base component.js's `emit` method.

I am going to close this one, but feel free to leave further question if you have.

**Comment by xxRockOnxx** [comment]
Pretty sure there's no `detail`.

See https://github.com/material-components/material-components-web/blob/master/packages/mdc-menu/simple/index.js#L119

It only emit the `index` and `item` directly NOT

````
{
  detail: {
    index: //
   item: //
  }
}

**Comment by xxRockOnxx** [comment]
I rechecked up to base. Yes, you are right. It uses `emit` that emits `Custom Event` that has details. Maybe I'll just copy that as well instead.

**Comment by yeelan0319** [comment]
You are right the argument passed in to `this.emit` is without not wrapped by `detail`, but that is not the evt object being passed to the handler yet. It got wrapped later in the `mdc-base` defined method. 

screen shot 2017-07-07 at 16 05 26

**Pull request closed without merging**
