### PR TITLE
fix(scripts): Ensure determine-pkg-versions outputs correct info

### PR DESCRIPTION
**Pull request by traviskaufman**
- Ensure new version output by determine-pkg-versions is correct
- Ensure proper publishConfig flags are sent to UpdatedPackagesCollector

### CODE REVIEW

**Comment by traviskaufman** [comment]
@yeelan0319 actually going to make a few more changes here, so feel free to hold off on the review until I update the PR 😄 thanks!

**Comment by traviskaufman** [comment]
@yeelan0319 updated! Feel free to review

**Comment by yeelan0319** [comment]
Cool. I will give it a look tomorrow morning 👍

**Comment by traviskaufman** [comment]
TravisCI seems to be hanging on this PR...last two builds passed and branch update was merged in cleanly so going to squash and merge.

**Pull request merged**
