### PR TITLE
feat(bottom-navigation): Add bottom-navigation component

### LINKED ISSUE #59: Investigate making Bottom Navigation Component
Spec reference: https://material.io/go/design-bottom-navigation

Useful for mobile-specific sites and layouts.

> Copied from https://github.com/google/material-design-lite/issues/4502 @

### PR DESCRIPTION
**Pull request by TroyTae**
closes #59

### CODE REVIEW

**Comment by TroyTae** [comment]
@abhiomkar 
I almost finish this work.
And I need a help...
I deleted this code because there is type error. (https://github.com/material-components/material-components-web/pull/5022/commits/35f44a17fd45b361e1680a80a5c1a8993b0b3544)
But this code works fine.
I don't know cause of error.
Can you help me??

**Comment by TroyTae** [comment]
@abhiomkar 
Is this error complex thing?

**Comment by TroyTae** [comment]
Please reopen when you start review.

**Comment by karocksjoelee** [comment]
What's wrong with this?

**Pull request closed without merging**
