### PR TITLE
chore: Fixed the order of css animation shorthand values

### PR DESCRIPTION
**Pull request by tomdye**
Fixes: https://github.com/material-components/material-components-web/issues/4283
Supersedes: https://github.com/material-components/material-components-web/pull/4291

Re-orders animation mixins to put the animation name at the beginning.

### CODE REVIEW

**Comment by tomdye** [comment]
I signed it!

**Comment by tomdye** [comment]
Not a problem

**Comment by tomdye** [comment]
Thanks for merging @abhiomkar , when is the next release please?

**Comment by abhiomkar** [comment]
We follow 2-week release cycle. Next release is scheduled on Feb 4th.

**Pull request merged**
