### PR TITLE
fix(button): Button Size Is Incorrect

### LINKED ISSUE #1483: Dialog Button Size Incorrect
**What MDC-Web Version are you using?**
Online dialog example: https://material-components-web.appspot.com/dialog.html 

**What browser(s) is this bug affecting?**
All

**What are the steps to reproduce the bug?**
1. Review link: https://material-components-web.appspot.com/dialog.html 
2. Inspect dialog buttons
3. .mdc-button is using min-width: 88px;

**What is the expected behavior?**
Dialog buttons have a min-width: 64px; See Material Design documentation for "Button width and padding" https://material.io/guidelines/components/dialogs.html#dialogs-specs 

screen shot 2017-10-25 at 8 19 49 am

### PR DESCRIPTION
**Pull request by touficbatache**
Fixes and closes #1483

### CODE REVIEW

**Comment by touficbatache** [comment]
Yes, I saw that error on the guidelines page but the diagram is for the flat button. Should I change the `min-width` of all buttons in general or only the flat button's one?

**Comment by touficbatache** [comment]
Changed the title as the fix is for the button in general and not only for the dialog one.

**Comment by MeyerUX** [comment]
@kfranqueiro what's the process for the design team updating documentation? Do they do it on the fly, or during a release on: https://material.io/guidelines/material-design/whats-new.html ?

**Comment by touficbatache** [comment]
Well, anyway they _should_ do it on the fly...

**Comment by touficbatache** [comment]
Well, anyway they _should_ do it on the fly...

**Comment by MeyerUX** [comment]
@touficbatache agreed, but also making sure we have a good way to track documentation updates. Which right now it looks like the "what's new" is only tracking major releases. This button change would be a big nice-to-know for the guideline side.

**Pull request merged**
