### PR TITLE
docs(toolbar) Fixed Demo URL 404.

### PR DESCRIPTION
**Pull request by efroim102**
Supposedly this [commit](https://github.com/material-components/material-components-web/commit/c8f70a64661b7c2f1aa31c188506bf0fb9dc8bd5) should have fixed it, but it didn't.

### CODE REVIEW

**Comment by efroim102** [comment]
I signed it!

**Comment by efroim102** [comment]
Am I the one that needs to confirm? If yes how?

**Comment by amsheehan** [comment]
@efroim102 Nope, CLA-bot can't handle when a commit is made as a result of updating the branch to the latest master. You're all good!

Thanks again

**Comment by efroim102** [comment]
Good to hear, Is the PR going to be merged?

**Comment by amsheehan** [comment]
As soon as CI passes, we'll merge it

**Comment by amsheehan** [comment]
Thanks again @efroim102

**Comment by efroim102** [comment]
You're Welcome!

**Pull request merged**
