### PR TITLE
docs: Update button example in getting started

### PR DESCRIPTION
**Pull request by mirkobriga**
mdc-button html for getting started fix

### CODE REVIEW

**Comment by mirkobriga** [comment]
@googlebot I signed it!

**Comment by mirkobriga** [comment]
Nothing at all! Correct the site too https://material.io/develop/web/docs/getting-started/

**Comment by mirkobriga** [comment]
I created a new fork and a new pull request with the same fix #5371 ,  is what you need?

**Comment by allan-chen** [comment]
@mirkobriga Yes - thank you! Apologies, as travis seems to have had some problems

**Pull request closed without merging**
