### PR TITLE
feat(top-app-bar): fix top/left and transition with transform

### PR DESCRIPTION
**Pull request by TroyTae**
related with https://github.com/material-components/material-components-web/pull/5007#issuecomment-522843519

### CODE REVIEW

**Comment by abhiomkar** [comment]
Assigning this to @azakus since he recently made some changes.

**Comment by TroyTae** [comment]
@azakus 
Can you check this please? :)

**Comment by TroyTae** [comment]
@azakus 
Can you check this please? :)

**Comment by TroyTae** [comment]
Please reopen when you start review.

**Pull request closed without merging**
