### PR TITLE
fix(infrastructure): remove babel loader

### PR DESCRIPTION
**Pull request by moog16**
related https://github.com/material-components/material-components-web/issues/4225

### CODE REVIEW

**Comment by moog16** [comment]
we should have travis run this step. It looks like `npm run dist` covers both build/build:min. But on 2nd thought it would be nicer to see both `build` and `build:min` separately. I can open a PR to update.

**Comment by kfranqueiro** [comment]
Unit tests are also failing in IE11 due to a syntax error. I don't think we can completely remove babel-loader while we still have ES6-formatted unit tests...

It also occurs to me that even for purposes of just the typescript sources, we probably can't actually remove babel-loader until we remove all occurrences of `Object.assign`, which probably means we need to wait until after all of the modules are converted to typescript.

**Comment by moog16** [comment]
I added back the babel loader for `js` files. I believe it to be unnecessary to have it in both places (ts files and js files`

**Comment by moog16** [comment]
closing this PR...more to come in #4409

**Pull request closed without merging**
