### PR TITLE
docs(toolbar): Fixes demo link (again).

### PR DESCRIPTION
**Pull request by shyndman**

### CODE REVIEW

**Comment by efroim102** [comment]
@shyndman Than what's the reason for another PR? It's already fixed...

**Comment by shyndman** [comment]
The first fix didn't take. ;)

Looks like App Engine isn't configured to serve index.html by default.

**Comment by efroim102** [comment]
So I committed a fix to your fix already #628.

**Comment by amsheehan** [comment]
@shyndman, we actually merged a fix to the fix earlier today 😄 

Closing this

**Comment by efroim102** [comment]
Quick Question, When are these changes deployed?

**Comment by amsheehan** [comment]
@efroim102 They will be deployed during our next release (this coming monday)

I am also reopening because it looks like there are two instances of the toolbar demo URL in the README. @efroim102 your PR earlier addressed one of them, this one will fix the other.

Thanks @shyndman for catching that.

**Comment by efroim102** [comment]
Oh ok, good to hear. Thanks for your help 😄 .

**Comment by amsheehan** [comment]
Nobody panic, CLA-bot does that if we update the branch. Everything is still fine. 👍

**Comment by efroim102** [comment]
@shyndman @amsheehan One of those 2 instances with the bad URL is actually commented out...

**Comment by shyndman** [comment]
The commented out tags are uncommented when building the documentation site.

Which I'm now realizing is a little confusing. I'm going to think on it.

**Comment by efroim102** [comment]
@shyndman Yep, for some reason I got confused with HTML, It's a markdown document that uses html comments to do custom parsing for clickable images...

**Comment by amsheehan** [comment]
@shyndman Feel free to continue thinking on how to best account for this quirk, but I'm going to merge this since any change to this part of the README should start from a solid foundation anyway. 👍

**Pull request merged**
