### PR TITLE
fix(menu): Allow anchor links as menu list items

### PR DESCRIPTION
**Pull request by jamesmfriedman**
The current logic prevents anchor links from firing when clicked on in the menu, a fairly common case.
fixes: #3486

### CODE REVIEW

**Comment by williamernest** [comment]
This doesn't work when the user clicks on the text or graphic of the link. We can set `pointer-events: none;` on the `mdc-list-item__text` and `mdc-list-item__grapic` classes when the `mdc-list-item` is a link. 

Adding the following to the end of the `mdc-menu` 
```
.mdc-menu {
...
  //stylelint-disable selector-max-type, selector-no-qualifying-type
  a.mdc-list-item .mdc-list-item__text,
  a.mdc-list-item .mdc-list-item__graphic {
    pointer-events: none;
  }
  // stylelint-enable selector-max-type, selector-no-qualifying-type
}
```

**Comment by jamesmfriedman** [comment]
Ah, yeah that makes sense.

**Comment by williamernest** [comment]
@jamesmfriedman Can you give me access to your repo to add this snippet?

**Comment by jamesmfriedman** [comment]
Sorry for the delay. Added you as a collaborator.

**Comment by jamesmfriedman** [comment]
Thanks @williamernest!

**Comment by yguedidi** [comment]
@jamesmfriedman @williamernest thanks for the fix! But it looks like it doesn't solve the following comment: https://github.com/material-components/material-components-web/issues/3486#issuecomment-423485685

**Comment by williamernest** [comment]
@yguedidi we set pointer events none on the elements within the list to ensure the anchor tag gets clicked and we don't prevent default on the event. Any custom markup you add inside the list item should also set pointer events to none.

**Pull request merged**
