### PR TITLE
fix(checkbox): screenshot test golden update

### PR DESCRIPTION
**Pull request by moog16**
Fixing checkbox screenshot test. SVG has changed on Firefox.

### CODE REVIEW

**Comment by abhiomkar** [comment]
This test was flaky for me earlier. Do you want to remove autofocus?

**Comment by abhiomkar** [comment]
Or let’s move autofocus to unchecked checkbox.

**Comment by moog16** [comment]
@abhiomkar how will moving autofocus fix the issue?

**Comment by abhiomkar** [comment]
@moog16 Seems like the ripple z position is flaky with the check mark icon. We can avoid this flaky test by moving the focus to unchecked checkbox.

**Pull request merged**
