### PR TITLE
Docs/snackbar update format

### PR DESCRIPTION
**Pull request by ALMaclaine**
I updated the snackbar readme to the correct format. I would say it's about 90% converted. Some of the information in the readme didn't fully fit with the format specified, but I thought better to leave it at the bottom than delete entirely.

From my understanding, the format is correct up to "Responding to a Snackbar Action", at that stage there are slight deviations from the specified format. From my understanding of the template, the example sections "Responding to a Snackbar Action" and "Keep snackbar when the action button is pressed" should be deleted, but I didn't want to do so without making an issue about it.

Also the "Usage Within Frameworks" section is not complete because snackbar does not have an adapter, so I was unsure how to grok what that section was saying because it seemed to match the foundation API. Again, didn't want to make a change without making an issue about it.

Finally, I'm not sure if the "Avoiding Flash-Of-Unstyled-Content (FOUC)" should be included either, it doesn't fit the format.

I believe this version of the readme more closely matches the prescribed format. I think it's a decent intermediate step towards fully converting the snackbar readme to the correct format. I intend to see it through regardless if this PR is accepted, but I think it would be easier to file issues on a 90% converted readme over a radically different format.

### CODE REVIEW

**Comment by ALMaclaine** [comment]
I have the CLA signed and I didn't change anything since my PR yesterday.

**Comment by ALMaclaine** [comment]
I have the CLA signed and I didn't change anything since my PR yesterday.

**Comment by ALMaclaine** [comment]
Going to try to close this one and do a PR with a freshly created README

**Comment by ALMaclaine** [comment]
How do I resolve this situation? I have my CLA signed, I'm the only contributor on my fork, it seems an old contributor doesn't have a CLA signed?

**Comment by kfranqueiro** [comment]
From the bot's message, I think this applies:

> If you authored these, maybe you used a different email address in the git commits than was used to sign the CLA

Judging by the commit list, it looks like your git is configured with a different e-mail that isn't linked with your github account. You can tell because https://github.com/material-components/material-components-web/pull/3370/commits doesn't show your github username and avatar on the commits. I'm not sure how this happened, since your first PR that we merged was linked fine. (Compare to https://github.com/material-components/material-components-web/pull/3355/commits which does show your github username/avatar.)

I'm not sure whether you're using a git front-end, but the command-line fix would be `git config user.email correct@email.here` (or `git config --global ...` if you want to fix it everywhere and haven't configured it specifically for this repository). Then you'll need to either amend the commits on this branch to reset the author, or (probably easier) just copy the content into a new branch and make a new commit after the email is fixed.

**Comment by ALMaclaine** [comment]
Thank you.

**Pull request closed without merging**
