### PR TITLE
fix(drawer): Add exports for Dismissible, Modal and util

### PR DESCRIPTION
**Pull request by trimox**
- Add export for `./dismissible/foundation.js`
- Add export for `./modal/foundation.js`
- Add export for `./util.js`

### CODE REVIEW

**Comment by trimox** [comment]
travis-ci reported issues with closure compiler.

**Comment by kfranqueiro** [comment]
Thanks so much for catching this! I believe the additional closure compiler errors are due to these modules originally not being visible to our closure test script. We're working on fixing them now and will send a new PR when it's ready.

**Comment by kfranqueiro** [comment]
I sent #3424 to fix this and the closure tests. Thanks again!

**Comment by trimox** [comment]
@kfranqueiro Not a prob! Glad to help.

**Pull request closed without merging**
