### PR TITLE
fix(menu): Fix wrong menu styling properties

### LINKED ISSUE #783: MDC Simple Menu
Hey,
I was making a template for my web app when I saw that the MDC Simple Menu does not look like the menu from the Material Design guidelines page. On the left we have MDC and on the right we have Material Design guidelines's menu.
mdc2
It's actually different in: 

1. The `font-size` which should be `16px`.
2. The `font-weight` which should be `400`.
3. The `min-width` which should be `170px`.
4. The `letter-spacing` which should be `0.05px`. (Should it be more or less than 0.05px? @robzenn92)

And with all these changes, the menu will look _**exactly**_ like the one on Material Design guidelines page. On the left we have MDC and on the right we have Material Design guidelines's menu.
mdc

### PR DESCRIPTION
**Pull request by Touficbatache**
Fixes #783 @amsheehan

### CODE REVIEW

**Comment by Touficbatache** [comment]
Yes it does! Totally missed that :)

**Comment by Touficbatache** [comment]
@amsheehan What's that error showing up? Do I need to do anything?

**Comment by amsheehan** [comment]
You do not. When we update the branch in Github it makes a commit on our behalf which throws off googlebot. Once CI passes I'll merge this

**Comment by Touficbatache** [comment]
Oh okay! Thanks. Would you mind taking a look at this issue?
https://github.com/material-components/material-components-web/issues/790

**Comment by amsheehan** [comment]
All issues are triaged twice per week in the order they get filed. 👍

**Comment by Touficbatache** [comment]
Okay, no problem :sweat_smile:

**Pull request merged**
