### PR TITLE
fix(slider): Fix for slider position being out of sync on absolutely positioned parent elements

### LINKED ISSUE #5128: [mdc-slider] Pointer's and slider's positions are out of sync in mdc-dialog
## Bug report
When parent component is scrollable and scrolled, slider in MdcDialog is "out of sync" exactly the amount the parent component is scrolled.

### Steps to reproduce
1. Go to https://stackblitz.com/edit/angular-mdc-slider-resize-bug-9ivgw4
2. scroll to the left
3. open dialog from 'Open' button
4. try to slide the slider

### Actual behavior
if I click on a slider track, the slider pin moves away from the point I clicked

### Expected behavior
if I click on a slider track, the slider pin moves to the point I clicked 

### Screenshots
The exmaple with the erroneous behaviour is in https://stackblitz.com/edit/angular-mdc-slider-resize-bug-9ivgw4

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web          | 3.2.1
| Browser          | Chrome 77.0.3865.90
| Operating System | Ubuntu 18.04.3 LTS

### PR DESCRIPTION
**Pull request by CyborgSemon**
Fixes #5128

### CODE REVIEW

**Comment by asyncLiz** [comment]
@CyborgSemon thanks for this PR, I apologize for getting to it so late.

Your approach seems good to me! Can you rebase master onto this branch?

**Comment by CyborgSemon** [comment]
tbh I forgot that this PR was here xD
Rebasing didn't seem to work. What should my next steps be?

**Comment by CyborgSemon** [comment]
Kind of odd that this commit is breaking CLA
Screen Shot 2020-01-18 at 11 06 49 AM

**Comment by asyncLiz** [comment]
Might be easier to close and open a new PR fresh from master since there's not a lot of complicated changes.

Do you want me to do that?

**Comment by CyborgSemon** [comment]
I can do that. I'll link to the new one and then close then one when its open

**Comment by CyborgSemon** [comment]
Moved to #5492

**Pull request closed without merging**
