### PR TITLE
docs: Update MDCTopAppBar js import

### LINKED ISSUE #4554: MDCTopAppBar README should not import index file
In the MDCTopAppBar README [here](https://github.com/ALMaclaine/material-components-web/blob/master/README.md#javascript).

The import statement should not import the `/index` but rather the package name.

```js
// From
import {MDCTextField} from '@material/textfield/index';

// To
import {MDCTextField} from '@material/textfield';
```

As per the [importing-js.md](https://github.com/material-components/material-components-web/blob/master/docs/importing-js.md#es-modules) and #4509

### PR DESCRIPTION
**Pull request by ALMaclaine**
Updated the MDCTopAppBar README to use correct import js format, including package name without index

Fixes #4554

### CODE REVIEW

**Comment by Richienb** [comment]
By removing `/index`, the code is made much slower.

**Comment by ALMaclaine** [comment]
@Richienb will you please add this comment to #4554 also. I'm attempting to fix inconsistencies in docs/code compared to the expected standard and have no influence on the standard itself.

**Comment by Richienb** [comment]
@ALMaclaine Done.

**Comment by moog16** [comment]
@ALMaclaine please comment "I signed it". It will trigger the CLA approval

**Comment by ALMaclaine** [comment]
I signed it

**Comment by moog16** [comment]
@abhiomkar I think you did a commit with your personal account. Can you login to your personal account and comment "I signed it"?

**Comment by abhiomkar** [comment]
I signed it

**Pull request merged**
