### PR TITLE
Fix for #1619 & #579 & #225

### PR DESCRIPTION
**Pull request by jonhue**
@amsheehan 

Building on @jamesmfriedman 's proposal, I found that this solution is working for me.

Fixing #1619, #579

### CODE REVIEW

**Comment by jamesmfriedman** [comment]
@kfranqueiro it seems that this PR was based off some work I did in my React lib. In my code, I do a check in the event path to see whether or not I should close it.

@jonhue, take a look.

https://github.com/jamesmfriedman/rmwc/blob/master/src/Base/withMDCDrawer.js#L36

**Comment by jonhue** [comment]
@kfranqueiro 

It should work as intended now.

**Comment by jonhue** [comment]
This should fix #225 as well.

**Comment by jonhue** [comment]
@kfranqueiro 

I'd love it, if this could be merged!

**Comment by jonhue** [comment]
@acdvorak @lynnjepsen 

Why doesn't this get merged?

**Comment by kfranqueiro** [comment]
We've merged 3e173e1ddc3bff5c7c9c2d794eeb36a9354ec98c (based on #1138) which resolves this by completely removing `stopPropagation` from the drawer code.

**Comment by jonhue** [comment]
@kfranqueiro When can I expect the changes to be released?

**Comment by kfranqueiro** [comment]
Our next release should be next Monday (we skipped one release cycle due to the holidays).

**Comment by jamesmfriedman** [comment]
Awesome, I'm looking forward to this one! It also seems like the temporary drawer is suffering from some animation issues on the newest iOS safari, but it could very likely be related to the hacky workaround I had to implement to fix this in RMWC.

**Pull request closed without merging**
